### ISSUE TITLE
[Feature Request] Serve IntersectionObserver to all Desktop Safari versions

### ISSUE THREAD

**Issue by mq2thez** [Financial-Times/polyfill-library#1192]
Hey folks!

As part of [this issue](https://github.com/Financial-Times/polyfill-library/issues/1082), IntersectionObserver is (happily) served to all mobile safari users.

However, we've noticed that a large number of desktop Safari users are also seeing the issue.

To give a sense of numbers:
- we've been averaging ~2.3k events per day of `Can't find variable: IntersectionObserver` per day coming from Desktop Safari
- Sentry is showing us that all of the events are coming from Safari v14.0-15.4 (the latest version)

We're hoping that the IntersectionObserver polyfill can be added to always be served to Desktop Safari users as well as mobile users.

Thanks!

**Comment by JakeChampion** [comment]
> Hey folks!
> 
> As part of [this issue](https://github.com/Financial-Times/polyfill-library/issues/1082), IntersectionObserver is (happily) served to all mobile safari users.
> 
> However, we've noticed that a large number of desktop Safari users are also seeing the issue.
> 
> To give a sense of numbers:
> 
>     * we've been averaging ~2.3k events per day of `Can't find variable: IntersectionObserver` per day coming from Desktop Safari
> 
>     * Sentry is showing us that all of the events are coming from Safari v14.0-15.4 (the latest version)
> 
> 
> We're hoping that the IntersectionObserver polyfill can be added to always be served to Desktop Safari users as well as mobile users.
> 
> Thanks!

Do you know what is causing those user agents to jot have Intersection Observer?

**Comment by mq2thez** [comment]
I've no idea -- I assume it's a similar mechanism to what's causing problems for mobile safari, something at the OS or browser level.

**Comment by romainmenke** [comment]
At least according to [this tweet](https://twitter.com/smfr/status/1456298972985708545?s=20&t=qQgFYPupuT4iIAgStBK4Hg) this is not something that is done on purpose and is possibly a bug.

Would be unfortunate if we need to keep shipping the polyfill indefinitely.

**Comment by romainmenke** [comment]
- Can you share anything about the percentage of iOS users that are affected?
- Which user agents are affected?
- Is there an existing safari/webkit bug report?

**Comment by romainmenke** [comment]
> Sentry is showing us that all of the events are coming from Safari v14.0-15.4 (the latest version)

@mq2thez Are there any events from Safari 12 or 13?
Seems very specific that this is not affecting every Safari version (after support landed)

**Comment by mq2thez** [comment]
@romainmenke As I mentioned above, iPad OS sends MacOS useragent strings now, so since iPadOS (iOS 13) was released, there's no way to detect iPad vs Mac via user agent string.

Via Sentry, here is a breakdown of the number of "events" seen by browser on one of the groupings of issues we're seeing in the last 14 days. We only serve Sentry's SDK to 20% of users, so it's not unreasonable to guess that the actual numbers are ~5x this.

|value               |times_seen|
|--------------------|----------|
|Mobile Safari 13.0  |2         |
|Mobile Safari 13.0.1|24        |
|Mobile Safari 14.1.2|6         |
|Mobile Safari 15.0  |4         |
|Mobile Safari 14.0  |6         |
|Mobile Safari 13.1.1|2         |
|Mobile Safari 15.5  |6         |
|Mobile Safari 13.0.5|30        |
|Mobile Safari 15.4  |9         |
|Safari 13.0.5       |648       |
|Firefox 91.0        |63        |
|Safari 13.0.3       |296       |
|Safari 13.0.1       |66        |
|Safari 12.1.2       |160       |
|Safari 13.1.1       |76        |
|Safari 15.5         |624       |
|Safari 12.1.1       |37        |
|Safari 14.0.1       |464       |
|Safari 13.1         |138       |
|Safari 14.0         |624       |
|Safari 14.1         |178       |
|Safari 13.0.4       |104       |
|Safari 15.4         |5089      |
|Safari 12.0.1       |2         |
|Safari 12.0.3       |12        |
|Safari 13.1.2       |316       |
|Safari 15.4.1       |18        |
|Safari 14.0.2       |294       |
|Safari 15.1         |1577      |
|Safari 15.2         |1097      |
|Safari 15.0         |659       |
|Safari 14.1.2       |6416      |
|Safari 14.1.1       |827       |
|Safari 14.0.3       |2223      |
|Safari 15.3         |6621      |

As you can see from the breakdown, our most significant problems occur in Safari v14 and 15, but that lines up very closely with our actual usage numbers -- we have relatively few users still on older versions of iOS, and the vast majority of our iOS traffic is coming from 14/15.

**Comment by romainmenke** [comment]
So basically **a lot of events** from all versions ever since it should have been supported natively.

Do you know if there was ever a bug report filed with webkit/safari?
Anything we can use to track a fix there?

My main concern is that we might never be able to remove this hack because we have no way to test that it is broken or fixed from our perspective.

**Comment by mq2thez** [comment]
I do not know, unfortunately.

**Comment by romainmenke** [comment]
Reported via feedback assistant : https://feedbackassistant.apple.com/feedback/10032713
This link won't work for anyone else but then I won't lose track of it.

------------

@jensimmons This is a tricky one but maybe you can ping the right people from the Safari/Webkit team to get the ball rolling?

_recap :_

As far as we know some users of Safari have a version with `IntersectionObserver` should be supported but `IntersectionObserver` is still `undefined`.

We (contributors of polyfill-library) do not have direct contact with any such user and can not ask them to file reports.

**Comment by romainmenke** [comment]
https://twitter.com/gsnedders/status/1536854518696132609

@gsnedders said :

>I believe as of Safari 15.4 we reset all the experimental features on update, and 15.4 notably doesn’t appear in the GitHub issue comment, so… hopefully fixed (2)?

@mq2thez can you confirm that this is still an issue on Safari 15.4 and 15.5 at this time?
_sorting the table might make it more clear?_

**Comment by mq2thez** [comment]
@romainmenke I also responded to the tweet, but: according to that table, 5107 hits (in 25% of users, so closer to 24k hits in 14 days at 100% traffic) to 15.4.0/15.4.1 in 14 days for (what we assume are) iPad users makes me think this still a significant issue.

**Comment by Ahmad-S792** [comment]
Could it be one of the following issue?

Webkit Bug - https://bugs.webkit.org/show_bug.cgi?id=196729 ; https://bugs.webkit.org/show_bug.cgi?id=241493

**Comment by mq2thez** [comment]
Hey @Ahmad-S792, since the bug is that IntersectionObserver is undefined, I do not think that either of those applies.

**Comment by mq2thez** [comment]
@romainmenke We're still seeing thousands of errors per day related to this -- would it be possible to get the fix merged and revisit when it should _stop_ being served once you get a response from the Webkit team?

**Comment by romainmenke** [comment]
Would love to, but I am just a serial contributor, don't have write access :/

**Comment by mq2thez** [comment]
Ah bummer -- @JakeChampion, any chance we could get this merged in?

**Comment by JakeChampion** [comment]
> Ah bummer -- @JakeChampion, any chance we could get this merged in?

I don't have permissions on the repository anymore as I no longer work at the Financial Times.

**Comment by mq2thez** [comment]
Ah, double bummer. Do you know who we could ping for getting it merged? What's the current maintenance status of the project?

**Comment by mq2thez** [comment]
It appears that @chee was able to merge/release things back in May -- perhaps they can help here?

**Comment by gsnedders** [comment]
So, I've had it pointed out to me that it's disabled in WebKit1 (WebKitLegacy, WebView, UIWebView, etc.), and a variety of in-app-browsers still use UIWebView despite it being long-deprecated. The UA strings might give away whether they're IABs?

https://bugs.webkit.org/show_bug.cgi?id=231767 exists for enabling it on WebKit1.

**Comment by romainmenke** [comment]
@gsnedders Thank you for this!

----------

_I don't have a recent iPad so I can't install and run a test iOS app on a real device._

UA string for a UIWebView on a Simulated iPad device.

```
Mozilla/5.0 (iPad: CPU OS 15 5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

This would receive the polyfill.

-------

UA string for Safari on a Simulated iPad device.

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10 15 6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
```

This would **not** receive the polyfill.

-------

UI string for Safari on a Simulated iPhone device.

```
Mozilla/5.0 (iPhone; CPU iPhone OS 15 5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1
```

-------

| user agent | has InterSectionObserver | receives polyfill |
| ---- | ---- | ---- |
| Safari iPad (simulated) | yes | no |
| UIWebView iPad (simulated) | no | yes |
| Safari iPhone (simulated) | yes | yes |
| UIWebView iPad (simulated) | no | yes |

Is it possible that `WebKitLegacy` or `WebView` sets a different UA string than `UIWebView`?
This would not be unlikely given that `UIWebView` also differs from Safari.

Hoping to find that entry without IntersectionObserver that also doesn't receive the polyfill.

**Comment by gsnedders** [comment]
> Is it possible that WebKitLegacy or WebView sets a different UA string than UIWebView?

(They're all the same thing, just exposed via different API names in different places/platforms.)

> This would not be unlikely given that UIWebView also differs from Safari.

But no, WebKitLegacy and WebKit both have the same UA string, _unless_ the application embedding it adds a suffix which makes it more unique. And many applications (especially in-app-browsers!) add _a lot_ to that suffix.

(This is https://github.com/WebKit/WebKit/blob/97d96daa046c3ad2de4cf310fa1333e6f176bd05/Source/WebCore/platform/ios/UserAgentIOS.mm for iOS; `applicationName` defaults to "Mobile/15E148" on mobile.)

See, e.g. https://github.com/Financial-Times/polyfill-service/issues/990 for prior fun with IABs.

**Comment by romainmenke** [comment]
@mq2thez Can you share some of the exact UA strings that have the error?
Then I can check how these are handled by the UA parser in use here.

**Comment by Ahmad-S792** [comment]
IntersectionObserver to be enabled on Webkit1 just got committed:

https://github.com/WebKit/WebKit/commit/ea72d728429e3a0b627083a0f5b2a83967c4f111

It might resolved this in future versions.

**Comment by romainmenke** [comment]
Thank you @Ahmad-S792 for letting us know 🎉

**Comment by romainmenke** [comment]
@mq2thez Thank you for this!

That indeed seems to indicate that the requests are made from Safari and not a webview.
(if I am interpreting all the UA strings correctly)

@gsnedders Is there anything you can think of that we can do to confirm this?

Maybe something is really bugging out with the feature flags after all 🤷

**Comment by mq2thez** [comment]
Hey folks, just checking back again! @chee, do you have any idea when we might be able to see the PR merged? I hate to keep bugging people, but I'm not sure what other options we have here.

**Comment by romainmenke** [comment]
@mq2thez Was thinking about this more and does it sound ok to you to serve IntersectionObserver to `Safari <16` ?

That way we might need to bump this later but we still have no way at all to confirm the problem or a fix later on.

If new error reports surface for Safari 16 we will know it isn't fixed yet.

**Comment by romainmenke** [comment]
@mq2thez [v4.1.1](https://github.com/Financial-Times/polyfill-library/releases/tag/v4.1.1) was just released.

**Comment by mq2thez** [comment]
@romainmenke @JakeChampion @chee @gsnedders  We've gone from about 2k events per day down to about 45 events in the last 12h, so I think it's safe to say that this has definitely resolved our issues. Thank you so much!

Of the remaining events we're seeing, they are all coming from a mix of Chrome v51, Firefox 56, and... Mobile Safari 16.0. I'm not sure whether the iOS 16 ones are a problem, but I'll share the UA strings we got just in case. Is it possible that something about 16 isn't recognized properly yet?
```
Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1
// Note: WKWebView
Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

Of note: we do decently rigorous filtering of bots, including filtering out browsers which are lying about certain types of syntax support, but it's still possible that these are users lying about their user agent.

**Comment by romainmenke** [comment]
@mq2thez Has this issue come back now that Safari 16 is rolling out?

**Comment by Ahmad-S792** [comment]
There is another issue fixed - https://github.com/WebKit/WebKit/commit/b5701774e49ff045c17f405df13ad7d6edfd1f41

Which might be in Safari 16.1 or 16.2.. So it might fix more edge cases.

**Comment by mq2thez** [comment]
@romainmenke Thanks for the ping, I had made a reminder for myself to check but hadn't gotten around to it.

Yes, this has come back. It's not quite as many as before -- maybe 1k events in the last 14 days, all registering as Mobile Safari 16. Example UA strings here:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1

Mozilla/5.0 (iPhone; CPU iPhone OS 16_0_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1
```

Of note to me is the `Mobile/15E148` -- it means we're looking at UIWebView users, afaik. I think this does mean that the polyfills need to be updated to serve to 16.*.

**Comment by romainmenke** [comment]
> Apple
> Sep 28, 2022 at 11:55 PM
> There are changes in the latest update, build iOS 20B5056e, or macOS 22A5358e, that may have resolved this issue.
You can see the software build your device is running and check for the latest update by tapping on Settings > General > Software Update.
>
> Has this issue been resolved after installing the latest update?
If not, please use Feedback Assistant to let us know you are still experiencing it.

I got this reply on the bug I opened via Feedback Assistant.
I am unsure if this is about Safari 16.0 or a later version. (fixed or not fixed?)

@gsnedders Do you know if `macOS 22A5358e` is Safari 16.0?

**Comment by Ahmad-S792** [comment]
> > Apple
> 
> > Sep 28, 2022 at 11:55 PM
> 
> > There are changes in the latest update, build iOS 20B5056e, or macOS 22A5358e, that may have resolved this issue.
> 
> You can see the software build your device is running and check for the latest update by tapping on Settings > General > Software Update.
> 
> >
> 
> > Has this issue been resolved after installing the latest update?
> 
> If not, please use Feedback Assistant to let us know you are still experiencing it.
> 
> 
> 
> I got this reply on the bug I opened via Feedback Assistant.
> 
> I am unsure if this is about Safari 16.0 or a later version. (fixed or not fixed?)
> 
> 
> 
> @gsnedders Do you know if `macOS 22A5358e` is Safari 16.0?
> 
> 
> 
> ----
> 
> 
> 
> My Safari version is up to date and has this info :
> 
> 
> 
> > Version 16.0 (17614.1.25.9.10, 17614)

I think it might be macOS Ventura or iOS 16.1 considering the build version had 'e' in it to indicate beta build. Both of which have Safari 16.1 rather than 16.

**Comment by romainmenke** [comment]
Thank you @Ahmad-S792!

In that case we will be cautious and hopeful and update the config to `< 16.1`.

**Comment by mq2thez** [comment]
Yeah, unfortunately, we can't even really know until 16.1 is released.

**Comment by romainmenke** [comment]
This has been released in `v4.5.0`.
I will leave this ticket open to revisit this when `16.1` drops.

**Comment by Ahmad-S792** [comment]
Might not be fix for this issue but fixing ordering of IntersectionObserver: https://github.com/WebKit/WebKit/pull/4967

**Comment by gsnedders** [comment]
> Of note to me is the `Mobile/15E148` -- it means we're looking at UIWebView users, afaik. I think this does mean that the polyfills need to be updated to serve to 16.*.

Nah, the default WebKit UA string on mobile contains that—it doesn't imply anything about UIWebView or WKWebView.

> I got this reply on the bug I opened via Feedback Assistant.

What's the FB reference?

> @gsnedders Do you know if `macOS 22A5358e` is Safari 16.0?

I'm not on my work computer right now so I can't tell you exactly what it is, but that's some macOS Ventura beta, so Safari 16.1 on macOS Ventura should have it fixed, at least. \[Edit]: [Wikipedia claims](https://en.wikipedia.org/wiki/MacOS_Ventura#History) it's macOS Ventura Beta 9.

> I think it might be macOS Ventura or iOS 16.1 considering the build version had 'e' in it to indicate beta build. Both of which have Safari 16.1 rather than 16.

The 'e' doesn't signify it's a beta (plenty of the macOS Ventura betas have had build numbers ending in other letters).

**Comment by romainmenke** [comment]
> What's the FB reference?

https://feedbackassistant.apple.com/feedback/10032713

**Comment by gsnedders** [comment]
> > I got this reply on the bug I opened via Feedback Assistant.
> 
> What's the FB reference?

Oh, is this FB10032713? That was just resolved via https://bugs.webkit.org/show_bug.cgi?id=231767 and that shipped in Safari 16.0.

**Comment by romainmenke** [comment]
I really wish we could have some relative/weighted numbers for the occurrences :)

> Yes, this has come back. It's not quite as many as before -- maybe 1k events in the last 14 days, all registering as Mobile Safari 16. 

This might be less because Safari `16.0` adoption is still low or it is fixed and the remainder might be bots acting like Safari `16.0`.

For now I am going to assume that this is fixed with https://bugs.webkit.org/show_bug.cgi?id=231767 as stated by @gsnedders.
Even if there are still instances were a users doesn't seem to have `IntersectionObserver` available, Safari on iOS from `16.0` now does fully support it to the best of our knowledge.

I suggest we keep the config at `16.1` as released in the latest version of this library even when `16.0` might be sufficient. This gives us a bit of a buffer.

Thank you @gsnedders for following up here and in WebKit.
Thank you everyone for sharing insights and data.

**Comment by romainmenke** [comment]
@mq2thez Going to close this for now, but please let us know if this comes back in the future.

**Comment by gsnedders** [comment]
FWIW, I actually just moved FB10032713 _away_ from verify due to @mq2thez's reports of this still happening. Might not have any further guesses as to cause at this point, but… it would be good to keep track of it.

**Comment by romainmenke** [comment]
This is still an ongoing issue.

Seemingly relevant bug report in WebKit : https://bugs.webkit.org/show_bug.cgi?id=249827
