### ISSUE TITLE
Cannot redefine non-configurable property 'values' on <= IE11

### ISSUE THREAD

**Issue by k1sul1** [Financial-Times/polyfill-library#123]
I've included this before my bundle:
```
<script type='text/javascript' src='https://cdn.polyfill.io/v2/polyfill.min.js?features=default%2Ces6%2Cfetch&#038;ver=4.8.2'></script>
```

However, IE11 (and lower) crash on an error: 
![image](https://user-images.githubusercontent.com/2719615/30710244-9e930e98-9f0d-11e7-8b8a-8a4ed6583b8e.png)

**Comment by JakeChampion** [comment]
This has been fixed in recent releases of polyfill.io and polyfill-library 

![bs_win10_ie_11 0 5](https://user-images.githubusercontent.com/1569131/53190083-c1277800-3600-11e9-9c44-8bb2f4c07b7d.jpg)

**Comment by gdomorski** [comment]
The most recent release works 🎉

**Comment by hstaniszewski** [comment]
For me, the problem still occurs. Here is a reproduction link for IE11 https://jsfiddle.net/xk8afqbu/
