### ISSUE TITLE
AsyncIterator: Attempting to change value of a readonly property

### ISSUE THREAD

**Issue by jamesarosen** [Financial-Times/polyfill-library#711]
[type]: bug

## What
When including the `es2018` bundle, we get the following exception on some iOS devices.

## Details
The stack trace points to [the `asyncIterator` polyfill](https://github.com/Financial-Times/polyfill-library/blob/f0a9bb1646f076eebe0174f39e890f6e877ce6bd/polyfills/Symbol/asyncIterator/polyfill.js#L2).

## Additional information

Example user agents:

* `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 144.0.0.17.119 (iPhone12,1; iOS 13_5_1; en_CA; en-CA; scale=2.00; 828x1792; 217426887)`
* `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 148.0.0.26.120 (iPhone10,3; iOS 13_5_1; en_US; en-US; scale=3.00; 1125x2436; 226453516)`
* `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1`
* `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/114.0.318129667 Mobile/15E148 Safari/604.1`

Possibly related #230

**Comment by jamesarosen** [comment]
https://caniuse.com/#feat=mdn-javascript_builtins_symbol_asynciterator says that iOS Safari 13.5 doesn't have `asyncIterator` support but when I run that browser, I see
```js
'Symbol' in self && 'asyncIterator' in self.Symbol // true
```

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/polyfill-library/blob/f0a9bb1646f076eebe0174f39e890f6e877ce6bd/polyfills/Symbol/asyncIterator/config.toml#L15

That's odd to see because we configured that polyfill to not be served to iOS 13, it is only served to iOS 11 and lower. How are you making the polyfill bundle exactly? Are you forcing it to always load?

**Comment by jamesarosen** [comment]
We have our own instance of polyfill-service running, but it's pretty up-to-date.

You can see this on the `polyfill.io` version:

```
$ curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1" https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver,es2015,es2016,es2017,es2018,es2019 2>&1 | grep asyncIterator

…Object.defineProperty(Symbol,"asyncIterator"…
```

**Comment by jamesarosen** [comment]
`User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1` normalizes to `ios_saf/11.0.0`, but I think it should be `ios_saf/13.1.1`. I think [this](https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/481a0c299a80ba2a1e95f2420994d55ea2cd8c7a/lib/normalise-user-agent.vcl#L91-L93) is the block for that.

**Comment by romainmenke** [comment]
This is fixed.

https://polyfill.io/v3/polyfill.js?features=IntersectionObserver,es2015,es2016,es2017,es2018,es2019


```
/* Polyfill service v3.105.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: IntersectionObserver,es2015,es2016,es2017,es2018,es2019
 * 
 * - _ESAbstract.Get, License: CC0 (required by "RegExp.prototype.flags", "es2015")
 * - _ESAbstract.ToBoolean, License: CC0 (required by "RegExp.prototype.flags", "es2015")
 * - _ESAbstract.Type, License: CC0 (required by "RegExp.prototype.flags", "es2015")
 * - RegExp.prototype.flags, License: MIT (required by "es2015") */
```

**Comment by vanderhoop** [comment]
Hey @JakeChampion, we're still seeing this issue of attempting to overwrite the readonly and already available `Symbol.asyncIterator` API, specifically in iOS safari, versions 14.X and 15.X. 

Interestingly enough, we're not seeing this on Mac OS, even on the latest versions (14.X and 15.X). I suspect this is due to the user agent string of the iOS safari.s

We're on polyfill.io, version `3.108.0`

**Comment by klarstrup** [comment]
Still seeing this around on 3.110.1
